FROM java:8-jdk-alpine
COPY target/01-springbootfirstproj-0.0.1-SNAPSHOT.jar   /usr/app/
WORKDIR /usr/app
RUN sh -c  'touch 01-springbootfirstproj-0.0.1-SNAPSHOT.jar'
ENTRYPOINT ["java", "-jar", "01-springbootfirstproj-0.0.1-SNAPSHOT.jar"]